#ifndef STYLE_HPP
#define STYLE_HPP
namespace WinCape{
    namespace  WindowStyles {
		enum
		{
			BORDER = WS_BORDER,
			CAPTION = WS_CAPTION,
			CHILD = WS_CHILD,
			CHILD_WINDOW = WS_CHILDWINDOW,
			CLIP_CHILDREN = WS_CLIPCHILDREN,
			CLIP_CLIP_SIBLINGS = WS_CLIPSIBLINGS,
			DISABLED = WS_DISABLED,
			DIALOG_FRAME = WS_DLGFRAME,
			GROUP = WS_GROUP,
			HORIZONTAL_SCROLL = WS_HSCROLL,
			ICONIC = WS_ICONIC,
			MAXIMIZE = WS_MAXIMIZE,
			MAXIMIZE_BOX = WS_MAXIMIZEBOX,
			MINIMIZE = WS_MINIMIZE,
			MINIMIZE_BOX = WS_MINIMIZEBOX,
			OVERLAPPED = WS_OVERLAPPED,
			OVERLAPPED_WINDOW = WS_OVERLAPPEDWINDOW,
			POPUP = WS_POPUP,
			POPUP_WINDOW = WS_POPUPWINDOW,
			SIZE_BOX = WS_SIZEBOX,
			SYSTEM_MENU = WS_SYSMENU,
			TAB_STOP = WS_TABSTOP,
			THICK_FRAME = WS_THICKFRAME,
			TILED = WS_TILED,
			TILED_WINDOW = WS_TILEDWINDOW,
			VISIBLE = WS_VISIBLE,
			VERTICAL_SCROLL = WS_VSCROLL
		};
		namespace Extended {
			enum {
				ACEEPT_FILES = WS_EX_ACCEPTFILES,
				APP_WINDOW = WS_EX_APPWINDOW,
				CLIENT_EDGE = WS_EX_CLIENTEDGE,
				COMPOSITED = 0x02000000,
				CONTEXT_HELP = WS_EX_CONTEXTHELP,
				CONTROL_PARENT = WS_EX_CONTROLPARENT,
				DIALOG_MODAL_FRAME = WS_EX_DLGMODALFRAME,
				LAYERED = 0x00080000,
				LAYOUT_RIGHT_TO_LEFT = 0x00400000,
				LEFT = WS_EX_LEFT,
				LEFT_SCROLL_BAR = WS_EX_LEFTSCROLLBAR,
				LEFT_TO_RIGHT_READING = WS_EX_LTRREADING,
				MDI_CHILD = WS_EX_MDICHILD,
				NO_ACTIVE = 0x08000000,
				NO_INHERIT_LAYOUT = 0x00100000,
				NO_PARENT_NOTIFY = WS_EX_NOPARENTNOTIFY,
				//NoRedirectionBitmap = WS_EX_NOREDIRECTIONBITMAP,
				OVERLAPPED_WINDOW = WS_EX_OVERLAPPEDWINDOW,
				PALETTE_WINDOW = WS_EX_PALETTEWINDOW,
				RIGHT = WS_EX_RIGHT,
				RiGHT_SCROLL_BAR = WS_EX_RIGHTSCROLLBAR,
				RIGHT_TO_LEFT_READING = WS_EX_RTLREADING,
				STATIC_EDGE = WS_EX_STATICEDGE,
				TOOL_WINDOW = WS_EX_TOOLWINDOW,
				TOPMOST = WS_EX_TOPMOST,
				//TRANSPARENT = WS_EX_TRANSPARENT, Uncommenting this line result in compiler error
				WINDOW_EDGE = WS_EX_WINDOWEDGE
			};
		}
	}
	namespace ButtonStyles {
		enum
		{
			_3STATE = BS_3STATE,
			AUTO_STATE = BS_AUTO3STATE,
			AUTO_CHECKBOX = BS_AUTOCHECKBOX,
			AUTO_RADIO_BUTTON = BS_AUTORADIOBUTTON,
			BITMAP = BS_BITMAP,
			BOTTOM = BS_BOTTOM,
			CENTER = BS_CENTER,
			CHECKBOX = BS_CHECKBOX,
			//CommandLink = BS_COMMANDLINK,
			//DefCommandLink = BS_DEFCOMMANDLINK,
			DEFPUSH_BUTTON = BS_DEFPUSHBUTTON,
			//DefSplitButton = BS_DEFSPLITBUTTON,
			GROUP_BOX = BS_GROUPBOX,
			ICON = BS_ICON,
			FLAT = 32768,
			LEFT = BS_LEFT,
			LEFT_TEXT = BS_LEFTTEXT,
			MULTILINE = BS_MULTILINE,
			NOTIFY = BS_NOTIFY,
			OWNER_DRAW = BS_OWNERDRAW,
			PUSH_BUTTON = BS_PUSHBUTTON,
			PUSH_LIKE = BS_PUSHLIKE,
			RADIO_BUTTON = BS_RADIOBUTTON,
			RIGHT = BS_RIGHT,
			RIGHT_BUTTON = BS_RIGHTBUTTON,
			//SplitButton = BS_SPLITBUTTON,
			TEXT = BS_TEXT,
			TOP = BS_TOP,
			TYPE_MASK = 15,
			USER_BUTTON = BS_USERBUTTON,
			V_CENTER = BS_VCENTER
		};
	}
	namespace ClassStyles {
		enum
		{
			BYTE_ALIGN_CLIENT = CS_BYTEALIGNCLIENT,
			BYTE_ALIGN_WINDOW = CS_BYTEALIGNWINDOW,
			CLASS_DEVICE_CONTEXT = CS_CLASSDC,
			DOUBLE_CLICKS = CS_DBLCLKS,
			DROP_SHADOWS = 0x00020000,
			GLOBAL_CLASS = CS_GLOBALCLASS,
			HORIZONTAL_REDRAW = CS_HREDRAW,
			NO_CLOSE = CS_NOCLOSE,
			OWN_DEVICE_CONTEXT = CS_OWNDC,
			PARENT_DEVICE_CONTEXT = CS_PARENTDC,
			SAVE_BITS = CS_SAVEBITS,
			VERTICAL_REDRAW = CS_VREDRAW
		};
	}

    namespace ListViewStyles
    {
        enum {
            ALIGN_LEFT = LVS_ALIGNLEFT,
            ALIGN_MASK = LVS_ALIGNMASK,
            ALIGN_TOP = LVS_ALIGNTOP,
            AUTO_ARRANGE = LVS_AUTOARRANGE,
            EDIT_LABELS = LVS_EDITLABELS,
            ICON = LVS_ICON,
            LIST = LVS_LIST,
            NO_COLUMN_HEADER = LVS_NOCOLUMNHEADER,
            NO_LABEL_WRAP = LVS_NOLABELWRAP,
            NO_SCROLL = LVS_NOSCROLL,
            NO_SORT_HEADER = LVS_NOSORTHEADER,
            //OWNER_DATA = 0x1000,
            OWNER_DRAW_FIXED = LVS_OWNERDRAWFIXED,
            REPORT = LVS_REPORT,
            SHARE_IMAGE_LISTS = LVS_SHAREIMAGELISTS,
            SHOW_SEL_ALWAYS = LVS_SHOWSELALWAYS,
            SINGLE_SEL = LVS_SINGLESEL,
            SMALL_ICON = LVS_SMALLICON,
            SORT_ASCENDING = LVS_SORTASCENDING,
            SORT_DESCENDING = LVS_SORTDESCENDING,
            TYPE_MASK = LVS_TYPEMASK,
            TYPE_STYLE_MASK = LVS_TYPESTYLEMASK
        };
        namespace Extended {
            enum {
                AUTO_ARRANGE = 0x01000000,
                AUTO_CHECK_SELECT = 0x08000000,
                AUTO_SIZE_COLUMNS = 0x10000000,
                AUTO_BORDER_SELECT = 32768,
                CHECKBOXES = 4,
                COLUMN_OVERFLOW = 2147483648,
                COLUMN_SNAP_POINTS = 0x40000000,
                DOUBLE_BUFFER = 65536,
                FLAT_SB = 0x00000100,
                FULL_ROW_SELECT = 32,
                GRID_LINES = 1,
                HEADER_DRAG_DROP = 16,
                HEADER_IN_ALL_VIEWS = 33554432,
                HIDE_LABELS = 131072,
                INFO_TIP = 1024,
                JUSTIFY_COLUMNS = 2097152,
                LABEL_TIP = 16384,
                MULTIWORK_AREAS = 8192,
                ONE_CLICK_ACTIVATE = 0x00000040,
                REGIONAL = 512,
                SIMPLE_SELECT = 1048576,
                SINGLE_ROW = 0x00040000,
                SNAP_TO_GRID = 0x00080000,
                SUB_ITEM_IMAGES = 0x00000002,
                TRACK_SELECT = 8,
                //TRANSPARENT_BACKGROUND = -1,NOT FOUND!
                TRANSPARENT_SHADOW_TEXT = 8388608,
                TWO_CLICK_ACTIVATE = 128,
                UNDERLINE_COLD = 4096,
                UNDERLINE_HOT = 2048
            };
        }
    };
}
#endif // STYLE_HPP
